### ISSUE TITLE
Better naming

### ISSUE THREAD

**Issue by themouette** [themouette/fossil-core#9]
What do you think:
# solution 1
- Your **Application**
- Uses **Modules** bound to **root urls**
- Each Module can have several **Components**
- Each Component provides one or several **Views**
# Solution 2
- Your **Application**
- Uses **Modules** bound to **root urls**
- Each Module can have several **Widgets**
- Each widget provides one or several **Views**
# Solution 3
- Your **Application**
- Uses **Page** bound to **root urls**
- Each Page can have several **Modules**
- Each Modules provides one or several **Views**
# Solution 4
- Your **Application**
- Uses **Modules** bound to **root urls**
- Each Module can have several **Panels**
- Each widget provides one or several **Views**
# Yours ?

**Comment by willdurand** [comment]
2

**Comment by willdurand** [comment]
`suburls` really?

**Comment by themouette** [comment]
root urls ?

**Comment by themouette** [comment]
What about panels for the 3rd level ?

**Comment by themouette** [comment]
MAJ.
Je vote pour **Application** > **Module** > **Panel** > **View**

**Comment by themouette** [comment]
@fredgate @fmarchand @K-Phoen @flo-ITN vous en pensez quoi ?

**Comment by willdurand** [comment]
**Area** pour le niveau le plus bas ?

**Comment by themouette** [comment]
**Region**, **Zone** ?

**Comment by themouette** [comment]
**Tile** ?

**Comment by themouette** [comment]
So, I'd go for any of **Fragment** or **Region**

**Comment by fmarchand** [comment]
Maybe I forgot to tell you @themouette but I would go for Fragment ...
